#!/bin/bash

VERSION=$ROLLBACK_VERSION
APP_NAME="Java3"
TOMCAT_HOME="/opt/tomcat"
NEXUS_URL="http://10.0.2.15:8081/repository/java3/aarush/webapp/$VERSION/webapp-$VERSION.war"

echo "### Executing Final Rollback Fix ###"

# 1. Kill everything
export BUILD_ID=dontKillMe
sh $TOMCAT_HOME/bin/shutdown.sh || true
#pkill -9 -f "catalina" || true

# 2. Deep Clean
# We remove the webapp, the war, and the work cache
sudo rm -rf $TOMCAT_HOME/webapps/$APP_NAME
sudo rm -rf $TOMCAT_HOME/webapps/$APP_NAME.war
#sudo rm -rf $TOMCAT_HOME/work/Catalina/localhost/$APP_NAME

# 3. Download
echo "Downloading Version $VERSION..."
curl -u admin:123 -L -f -o $TOMCAT_HOME/webapps/$APP_NAME.war "$NEXUS_URL"

# 5. Start
sh $TOMCAT_HOME/bin/startup.sh

# 6. Wait for Extraction and Fix again
echo "Waiting for extraction..."
sleep 5
